import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { buildHermesCustomProvider } from "../adapters/hermes/claudeOauthBridge.js";
import { buildLettaOpenAICompatibleConfig } from "../adapters/letta/claudeOauthBridge.js";
import { normalizeBridgeUrl } from "../adapters/mastra/claudeOauthGateway.js";
import { rejectPathTraversal, sanitizeBranchComponent } from "./security.js";
import type { AutomationTask, RunnerFramework } from "./types.js";

export interface RunnerBridgeOptions {
  bridgeUrl: string;
  bridgeApiKeyEnv?: string;
}

export interface JobPlan {
  task: AutomationTask;
  checkout: {
    mode: "pull-request-head" | "branch";
    baseRef?: string;
    headRef?: string;
  };
  discoveryCommands: string[][];
  publishCommands: string[][];
  instructionFiles: string[];
}

export interface MockAutomationJobOptions {
  workspaceRoot: string;
  task: AutomationTask;
}

export interface MockAutomationJobResult {
  workspace: string;
  branchName: string;
  prBodyPath: string;
}

export function buildRunnerFrameworkConfig(framework: RunnerFramework, options: RunnerBridgeOptions): unknown {
  if (framework === "mastra") {
    return {
      provider: "claude-oauth",
      model: "claude-oauth/claude-oauth/sonnet",
      bridgeUrl: normalizeBridgeUrl(options.bridgeUrl),
      bridgeApiKeyEnv: options.bridgeApiKeyEnv ?? "CLAUDE_OAUTH_BRIDGE_API_KEY"
    };
  }

  if (framework === "hermes") {
    return buildHermesCustomProvider({
      bridgeUrl: options.bridgeUrl,
      apiKeyEnv: options.bridgeApiKeyEnv
    });
  }

  return buildLettaOpenAICompatibleConfig({
    bridgeUrl: options.bridgeUrl,
    apiKeyEnv: options.bridgeApiKeyEnv
  });
}

export function buildJobPlan(task: AutomationTask): JobPlan {
  const checkout = task.kind === "review-pr"
    ? {
        mode: "pull-request-head" as const,
        baseRef: task.prBaseRef ?? task.defaultBranch,
        headRef: task.prHeadRef
      }
    : {
        mode: "branch" as const,
        baseRef: task.defaultBranch ?? "main"
      };

  return {
    task,
    checkout,
    instructionFiles: ["README.md", "AGENTS.md", "CLAUDE.md", "CONTRIBUTING.md", "package.json"],
    discoveryCommands: [
      ["git", "status", "--short"],
      ["git", "diff"],
      task.kind === "review-pr" ? ["gh", "pr", "view", String(task.prNumber)] : ["gh", "issue", "view", String(task.issueNumber ?? "")]
    ],
    publishCommands: publishCommandsFor(task)
  };
}

export async function runMockAutomationJob(options: MockAutomationJobOptions): Promise<MockAutomationJobResult> {
  const safeRepoDir = rejectPathTraversal(options.task.repoFullName.replace("/", "-"));
  const workspace = join(options.workspaceRoot, safeRepoDir, options.task.id ?? "task");
  await mkdir(workspace, { recursive: true });

  const branchName = branchNameForTask(options.task);
  const prBodyPath = join(workspace, "PR_BODY.md");
  await writeFile(
    prBodyPath,
    [
      `# ${options.task.kind} for ${options.task.repoFullName}`,
      "",
      `Framework: ${options.task.framework}`,
      `Branch: ${branchName}`,
      "",
      "This artifact was generated by the local mock runner."
    ].join("\n"),
    "utf8"
  );

  return { workspace, branchName, prBodyPath };
}

function publishCommandsFor(task: AutomationTask): string[][] {
  if (task.kind === "review-pr") {
    return [
      ["gh", "pr", "review", String(task.prNumber), "--comment"],
      ["gh", "pr", "comment", String(task.prNumber)]
    ];
  }

  if (task.kind === "fix-issue") {
    return [
      ["gh", "pr", "create", "--fill"],
      ["gh", "issue", "comment", String(task.issueNumber)]
    ];
  }

  return [
    ["gh", "pr", "create", "--fill"],
    ["gh", "issue", "comment", String(task.issueNumber ?? "")]
  ];
}

function branchNameForTask(task: AutomationTask): string {
  if (task.kind === "review-pr") {
    return `agent/review-pr-${task.prNumber}`;
  }

  if (task.kind === "fix-issue") {
    return `agent/fix-issue-${task.issueNumber}`;
  }

  return `agent/research-and-patch-${sanitizeBranchComponent(String(task.issueNumber ?? task.id ?? "task"))}`;
}
